version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash scripts/run.sh 
    volumes:
      - .:/YangSpace
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
        SETTING_CHOICE: prod
